"""initial schema

Revision ID: 4b64a5c0b7cc
Revises:
Create Date: 2026-08-28 18:57:13.132674
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4b64a5c0b7cc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "devices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_identifier", sa.String(length=255), nullable=False),
        sa.Column("apns_token", sa.String(length=255), nullable=False),
        sa.Column("token_kind", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_devices_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("apns_token", name=op.f("uq_devices_apns_token")),
        sa.UniqueConstraint("user_id", "device_identifier", name=op.f("uq_devices_user_id")),
    )
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("room_name", sa.String(length=128), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("group", "direct", name="meetingkind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled", "active", "ended", "cancelled", name="meetingstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uses_waiting_room", sa.Boolean(), nullable=False),
        sa.Column("is_microphone_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_camera_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_speaker_enabled", sa.Boolean(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_meetings_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("room_name", name=op.f("uq_meetings_room_name")),
    )
    op.create_index(op.f("ix_meetings_code"), "meetings", ["code"], unique=True)
    op.create_index(op.f("ix_meetings_owner_id"), "meetings", ["owner_id"], unique=False)
    op.create_index(op.f("ix_meetings_starts_at"), "meetings", ["starts_at"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_replaced_by_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
    )
    op.create_index(
        op.f("ix_refresh_sessions_token_hash"), "refresh_sessions", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "call_sessions",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("initiated_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ringing",
                "active",
                "ended",
                "rejected",
                "cancelled",
                "missed",
                name="callstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiated_by_id"],
            ["users.id"],
            name=op.f("fk_call_sessions_initiated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_call_sessions_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_sessions")),
    )
    op.create_index(
        op.f("ix_call_sessions_meeting_id"), "call_sessions", ["meeting_id"], unique=False
    )
    op.create_table(
        "meeting_members",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("host", "moderator", "participant", name="meetingrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_members_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_meeting_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_members")),
        sa.UniqueConstraint("meeting_id", "user_id", name=op.f("uq_meeting_members_meeting_id")),
    )
    op.create_index(
        op.f("ix_meeting_members_meeting_id"), "meeting_members", ["meeting_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_members_user_id"), "meeting_members", ["user_id"], unique=False
    )
    op.create_table(
        "call_participants",
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["call_sessions.id"],
            name=op.f("fk_call_participants_call_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_call_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_participants")),
        sa.UniqueConstraint("call_id", "user_id", name=op.f("uq_call_participants_call_id")),
    )
    op.create_index(
        op.f("ix_call_participants_call_id"), "call_participants", ["call_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_participants_user_id"), "call_participants", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_participants_user_id"), table_name="call_participants")
    op.drop_index(op.f("ix_call_participants_call_id"), table_name="call_participants")
    op.drop_table("call_participants")
    op.drop_index(op.f("ix_meeting_members_user_id"), table_name="meeting_members")
    op.drop_index(op.f("ix_meeting_members_meeting_id"), table_name="meeting_members")
    op.drop_table("meeting_members")
    op.drop_index(op.f("ix_call_sessions_meeting_id"), table_name="call_sessions")
    op.drop_table("call_sessions")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_token_hash"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_meetings_starts_at"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_owner_id"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_code"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
